In [1]:
import numpy as np
import pandas as pd

In [2]:
df_jokes = pd.read_csv('JokeText.csv')
df_ratings1 = pd.read_csv('UserRatings1.csv')

In [3]:
df_jokes.head()

JokeId                                           JokeText
0       0  A man visits the doctor. The doctor says "I ha...
1       1  This couple had an excellent relationship goin...
2       2  Q. What's 200 feet long and has 4 teeth? \n\nA...
3       3  Q. What's the difference between a man and a t...
4       4  Q.\tWhat's O. J. Simpson's Internet address? \...

In [98]:
df_ratings1.head(20)

0      1      2      3      4      5      6      7      8      9  \
User1   15.10  14.90  11.75   5.83  15.15  11.75  14.76  13.30   7.43   8.59   
User2    1.21   9.13  11.99   5.39  15.39   9.22  11.60  11.07   1.31   5.34   
User3    6.50   7.09   7.82   9.90  17.52  11.26   4.61  11.50   1.60  14.37   
User4   17.14   6.12   6.94  10.05  16.26  16.65   2.48  17.28   4.85   2.86   
User5    1.21   9.42   9.42  18.98  17.67  18.25  14.08  12.52   0.34  12.48   
User6   19.22  19.37   6.07  19.27  13.45   1.89  14.42  12.72  19.08  19.13   
User7    5.97   8.45   6.36   3.01  15.44   3.25   9.85   4.13   6.46   4.81   
User8   13.11  10.92  17.52  10.49   9.42  12.14   9.76  18.06  12.82  17.52   
User9    6.36   6.65   3.54   6.60  11.26  10.34   6.99   3.35   6.60  11.36   
User10   2.33   4.85   6.75   8.35  14.03  11.84  15.19   9.71   6.46  18.83   
User11  13.06   1.75   6.02   9.42  16.41  12.91   1.55  13.30  11.75  18.93   
User12   0.63  19.13  19.27  19.37  19.17  18.93  19.27  16.41   9.66  19.22   
User13  12.28  11.75   0.05   0.53   6.80  10.78   1.12  14.37   8.30  15.34   
User14   8.83  13.64  16.50  14.51  15.87  14.17   3.11  11.99   6.12  15.87   
User15  16.75  18.25  15.44  11.80  15.68  17.38  13.30  14.51  11.89  13.74   
User16  18.40  13.16  17.77   9.37  17.91   9.27  12.77   7.28  13.54  13.74   
User17  17.38  14.85  15.39  14.32   2.38   4.76   6.50  15.83  14.13  15.00   
User18  16.07  13.40  14.13   6.84   0.44  11.84  12.96  14.08  11.36  12.67   
User19   9.47   0.68   1.26   4.71   2.57  15.05  18.64  18.20  19.03   6.89   
User20  13.40  18.01   7.86   1.94  16.94  12.18   6.46  16.26  15.29  18.30   

        ...     91     92     93     94     95     96     97     98     99  \
User1   ...   5.39  13.59  17.18  10.92  16.31   5.05   9.81  13.25  14.37   
User2   ...  11.21  12.86   9.95   8.25   8.98   9.03  14.13   8.16  12.96   
User3   ...   5.97   8.59  11.65   6.21  13.98   3.54   3.11   7.67   2.62   
User4   ...  16.36  14.71   4.81  16.26  13.93   7.43  11.07  12.33   9.66   
User5   ...  19.37  18.30  19.13   6.55  19.13  19.17  19.17  19.08  18.98   
User6   ...   8.88  12.28  13.79  13.74  11.94  11.99  13.45  19.17   8.45   
User7   ...   6.02   3.30  11.31  14.17  10.44   9.22   8.98  11.70  14.22   
User8   ...  13.59  12.09  11.21  11.21  11.21  15.34  11.94  13.06  13.59   
User9   ...  16.94  13.69  13.79  13.74  16.94  15.83  15.53  16.55  13.83   
User10  ...   4.08   7.77  14.17  15.97  11.12  10.78  14.76  17.86  12.09   
User11  ...  17.82  17.67  14.42   5.83  14.08   9.56  15.05  12.14   5.73   
User12  ...   0.15   0.05   0.73   0.10   0.44   0.19  19.27   0.24  19.27   
User13  ...  16.80   5.97   7.52  14.81  13.93  13.01  13.20  13.06   5.92   
User14  ...   9.03   9.71   4.66   8.40   4.61   4.76   2.86   2.91   9.66   
User15  ...   9.85  18.11  17.72  14.85  16.12  15.68  15.49  13.11  15.19   
User16  ...   8.01  12.77  10.53  16.12  13.40   1.21  11.70   9.47  17.43   
User17  ...  15.63  14.47  15.58  15.05  13.16  15.29   4.37  13.16   5.10   
User18  ...   1.26  10.63  12.48   0.78   3.11  10.68   6.17   1.12  10.97   
User19  ...  13.11  13.98  18.59  11.99  12.09  12.96   7.28  16.21   3.35   
User20  ...  10.00  10.10  11.02  14.22  10.49  11.70   9.71   9.37   9.71   

        average_rating  
User1          11.7470  
User2           9.4166  
User3           9.2565  
User4          10.7567  
User5          12.9420  
User6          11.5786  
User7           7.5782  
User8          11.0233  
User9          11.2542  
User10          8.1732  
User11         11.3191  
User12         10.9111  
User13         10.7264  
User14         10.9748  
User15         14.0460  
User16         11.4954  
User17         10.4843  
User18          9.4983  
User19         11.9616  
User20         12.1645  

[20 rows x 101 columns]

It's more convenient to replace this with a transposed version.

In [5]:
df_ratings1 = df_ratings1.transpose()[1:]
df_ratings1.head()

0     1     2     3     4     5     6     7     8     9   ...    90  \
User1  5.10  4.90  1.75 -4.17  5.15  1.75  4.76  3.30 -2.57 -1.41  ...  5.34   
User2 -8.79 -0.87  1.99 -4.61  5.39 -0.78  1.60  1.07 -8.69 -4.66  ...  3.59   
User3 -3.50 -2.91 -2.18 -0.10  7.52  1.26 -5.39  1.50 -8.40  4.37  ...  1.84   
User4  7.14 -3.88 -3.06  0.05  6.26  6.65 -7.52  7.28 -5.15 -7.14  ... -4.47   
User5 -8.79 -0.58 -0.58  8.98  7.67  8.25  4.08  2.52 -9.66  2.48  ... -0.29   

         91    92    93    94    95    96    97    98    99  
User1 -4.61  3.59  7.18  0.92  6.31 -4.95 -0.19  3.25  4.37  
User2  1.21  2.86 -0.05 -1.75 -1.02 -0.97  4.13 -1.84  2.96  
User3 -4.03 -1.41  1.65 -3.79  3.98 -6.46 -6.89 -2.33 -7.38  
User4  6.36  4.71 -5.19  6.26  3.93 -2.57  1.07  2.33 -0.34  
User5  9.37  8.30  9.13 -3.45  9.13  9.17  9.17  9.08  8.98  

[5 rows x 100 columns]

Some of the ratings are negative, ranging from -10 to 10. To avoid negative and positive ratings cancelling, I add 10 to the whole dataframe here.

In [6]:
df_ratings1 = df_ratings1.add(10, axis=0)

We also need an average rating feature.

In [7]:
df_ratings1['average_rating'] = df_ratings1.mean(axis=1)

Note I dropped a row that would correspond to the transposed JokeID, since the JokeID feature duplicated thee index, this was simply convenient.

# Recommender Outline
For some usere
1. Pick neighborhood (at least pick users who have rated the same jokes)
2. Calculate similarity between input user and every other neighbor in neighborhood (Pearson's)
3. Prediict based on the neighborhood

In [8]:
users = [col for col in df_ratings1.columns if col != 'average_rating']

In [55]:
def find_rated_jokes(ratings_matrix, user):
    user_ratings = ratings_matrix.loc[ratings_matrix.index==user].T
    user_ratings = user_ratings.loc[user_ratings.notna().values]
    rated_jokes = user_ratings.index
    return np.asarray(rated_jokes)[:-1] # drop 'average_rating'

example_user = 'User36701' # test case with known NaNs
example_rated = find_rated_jokes(df_ratings1, example_user) # test case with known NaNs
example_rated

array([4, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24,
       25, 26, 27, 28, 29, 30, 31, 34, 35, 37, 38, 39, 41, 44, 45, 46, 47,
       48, 49, 51, 52, 53, 55, 57, 60, 61, 62, 64, 65, 67, 68, 76, 87, 93],
      dtype=object)

In [56]:
def find_common_ratings(df, rated, N):
    '''
    Finds users that have rated the jokes in the list rated
    Parameters: df, a dataframe containing user ratings
                rated, a list of integers representing jokes the user has rated
                N, size of the neighborhood (ideally calculate similarity first, but this saves on computation)
    Returns: subset, a dataframe containing as rows users who have rated the jokes
            in "rated"
    '''
    subset = df.copy()
    for i in rated:
        subset = subset.loc[subset[i].notna()] # pretty sure this is slow/wrong, check in morning
    return subset[:N]

subset = find_common_ratings(df_ratings1, example_rated, 10000)
subset.head()

0      1      2      3      4      5      6      7     8      9  \
User1  15.10  14.90  11.75   5.83  15.15  11.75  14.76  13.30  7.43   8.59   
User2   1.21   9.13  11.99   5.39  15.39   9.22  11.60  11.07  1.31   5.34   
User3   6.50   7.09   7.82   9.90  17.52  11.26   4.61  11.50  1.60  14.37   
User4  17.14   6.12   6.94  10.05  16.26  16.65   2.48  17.28  4.85   2.86   
User5   1.21   9.42   9.42  18.98  17.67  18.25  14.08  12.52  0.34  12.48   

       ...     91     92     93     94     95     96     97     98     99  \
User1  ...   5.39  13.59  17.18  10.92  16.31   5.05   9.81  13.25  14.37   
User2  ...  11.21  12.86   9.95   8.25   8.98   9.03  14.13   8.16  12.96   
User3  ...   5.97   8.59  11.65   6.21  13.98   3.54   3.11   7.67   2.62   
User4  ...  16.36  14.71   4.81  16.26  13.93   7.43  11.07  12.33   9.66   
User5  ...  19.37  18.30  19.13   6.55  19.13  19.17  19.17  19.08  18.98   

       average_rating  
User1         11.7470  
User2          9.4166  
User3          9.2565  
User4         10.7567  
User5         12.9420  

[5 rows x 101 columns]

In [11]:
corr = subset[users].T.corr() # Pandas ignores NaNs by default

Next, calculate predictions.

In [102]:
def single_prediction(similarity_vector, rating_deviations, user_idx, joke):
    rating_dev_vector = rating_deviations[joke]

    # Sum over only other users, not input user
    similarity_vector = np.delete(similarity_vector, user_idx)
    rating_dev_vector = np.delete(rating_dev_vector, user_idx)

    numerator = np.dot(similarity_vector, rating_dev_vector) # weighted sum over other users of similaritiies and differences between rating and user mean
    denominator = np.sum(similarity_vector) # normaalizing term, sum of similarities between user and all other useers in neighborhood
    
    prediction = numerator/denominator
    
    return prediction

def predict_jokes(similarity_matrix, ratings_matrix, user, rated_jokes):
    user_idx = int(user.split('r')[1])
    user_mean = ratings_matrix['average_rating'][user]
    similarity_vector = similarity_matrix[user].values
    
    rating_deviations = ratings_matrix.sub(ratings_matrix['average_rating'], axis=0)[users].T.values

    predictions = []
    
    for joke in rated_jokes:
        predictions.append(single_prediction(similarity_vector, rating_deviations, user_idx, joke))

    predictions = np.asarray(predictions) + user_mean - 10 # Remove 10 which was added initially
    return predictions
    

predict_jokes(corr, subset, 'User99', [1,2,3, 20])

array([5.95853705, 5.80349167, 2.71969647, 6.66842115])

In [115]:
a = [4,2,10]
b = [1,2,3]

c = list(zip(a,b))

sort = sorted(c, key=lambda x:x[0], reverse=True)

a, b = list(zip(*sort))

In [118]:
def sort_joke_idx(rated_jokes, predictions):
    '''
    Sorts indices of jokes by predicted ratings
    '''
    zipped_rating_predictions = list(zip(predictions, rated_jokes))
    
    sorted_zip = sorted(zipped_rating_predictions, key=lambda x: x[0], reverse = True)
        
    sorted_predictions, sorted_idxs = list(zip(*sorted_zip))
    
    return sorted_predictions, sorted_idxs

In [122]:
def give_recommendations(user, ratings_matrix, joke_matrix, n_neighbors):
    
    rated_jokes = find_rated_jokes(ratings_matrix, user)

    neighbors = find_common_ratings(ratings_matrix, rated_jokes, n_neighbors)
    users = [col for col in neighbors.columns if col != 'average_rating']

    similarity_matrix = neighbors[users].T.corr()

    predictions = predict_jokes(similarity_matrix, neighbors, user, rated_jokes)
    
    sorted_predictions, sorted_idxs = sort_joke_idx(rated_jokes, predictions)

    joke_recommendations = df_jokes.iloc[list(sorted_idxs)]
    
    joke_recommendations['predictions'] = list(sorted_predictions)
    
    return joke_recommendations

give_recommendations('User50', df_ratings1, df_jokes, 100).values

C:\Users\Patrick\AppData\Local\Temp/ipykernel_29064/2948288095.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  joke_recommendations['predictions'] = list(sorted_predictions)


array([[49,
        'A guy goes into confession and says to the priest, "Father, I\'m 80 years\nold, widower, with 11 grandchildren. Last night I met two beautiful flight\nattendants. They took me home and I made love to both of them. Twice."\n\nThe priest said: "Well, my son, when was the last time you were in\nconfession?"\n "Never Father, I\'m Jewish."\n "So then, why are you telling me?"\n "I\'m telling everybody."\n',
        5.60380270903077],
       [88,
        "A radio conversation of a US naval \nship with Canadian authorities ... \n\nAmericans: Please divert your course 15 degrees to the North to avoid a\ncollision.\n\nCanadians: Recommend you divert YOUR course 15 degrees to the South to \navoid a collision.\n\nAmericans: This is the Captain of a US Navy ship.  I say again, divert \nYOUR course.\n\nCanadians: No.  I say again, you divert YOUR course.\n\nAmericans: This is the aircraft carrier USS LINCOLN, the second largest ship in the United States' Atlantic Fleet. We are 